#!/bin/sh
#
# Copyright (C) 2015 by Goldbassist, member of OpenMake.cc
# http://www.rasplay.org, https://github.com/rasplay
#
# Part of raspi-config http://github.com/asb/raspi-config
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
# 
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#

sudo sed -i "s/# ko_KR.EUC-KR EUC-KR/ko_KR.EUC-KR EUC-KR/" /etc/locale.gen
sudo sed -i "s/# ko_KR.UTF-8 UTF-8/ko_KR.UTF-8 UTF-8/" /etc/locale.gen
sudo locale-gen
sudo locale -a

sudo sed -i 's/LANG=en_GB.UTF-8/LANG=ko_KR.EUC-KR/' /etc/default/locale

if [ -f "/home/pi/.dmrc" ]; then
    grep -q 'Language=ko_KR.utf8' /home/pi/.dmrc
    if [ ! $? -eq 0 ] ; then
        sed -i '$a\Language=ko_KR.utf8' /home/pi/.dmrc
    fi
fi
